sudo: false

notifications:
  email: false

language: python
python: 2.7
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
    - yui-compressor
    - postgresql-9.6-postgis-2.3
    # This is needed so that pg_config works for psycopg2's version detection
    - postgresql-server-dev-9.6

install:
  - wget ${ES_DOWNLOAD_URL}
  - tar xzf elasticsearch-${ES_VERSION}.tar.gz
  - elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - pip install -U pip
  - bundle update json
  - bundle install --deployment --path ../gems --binstubs ../gem-bin
  # Now install the rest of the required Python packages:
  - CFLAGS="-O0" pip install -r requirements.txt
  - pip install python-coveralls
  - pip check
  # Create a basic general.yml file:
  - sed -r
    -e "s,(POMBOLA_DB_USER:) 'sayit',\\1 'postgres',"
    -e "s,(POMBOLA_DB_NAME:) '',\\1 'pombola',"
    -e "s,(DJANGO_SECRET_KEY:) '',\\1 'notatallsecret',"
    conf/general.yml-example > conf/general.yml

before_script:
  - createdb -U postgres pombola
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d pombola
  - ./manage.py migrate --noinput
  - ./manage.py collectstatic --noinput
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - ./run-tests --coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - coveralls

env:
  - ES_VERSION=0.90.13 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz CC_TEST_REPORTER_ID=44bde58b55e4b1b6e54683a0a66a21c693118fde0a2111d51037b11be91f5673
