dist: trusty

notifications:
  email: false

services:
  - docker

script:
  - docker-compose up -d db elasticsearch
  - bin/wait-for-deps.sh
  - "docker-compose run coverage run -a --source=pombola,pombola_sayit,wordcloud ./manage.py test --settings=pombola.settings.tests_south_africa"

after_script:
  # Log output in case issues occurred where this can help us debug quicly
  - docker-compose logs db elasticsearch

  # Run codecov passing appropriate codecov.io CI environment variables to container
  - "docker-compose run --rm `bash <(curl -s https://codecov.io/env)` web codecov"
