version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: pombola
    depends_on:
      - db
    volumes:
      - app-data:/app-data
      - .:/app
    environment:
      - DATABASE_URL=postgresql://pombola:pombola@db/pombola
      - POMBOLA_DATADIR=/app-data
      - DJANGO_DEBUG=TRUE
      - DJANGO_SECRET_KEY=not-secret-in-dev
      - ELASTICSEARCH_URL=elasticsearch:9200
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=pombola
      - POSTGRES_PASSWORD=pombola
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./bin/postgis-legacy.sh:/docker-entrypoint-initdb.d/y-postgis-legacy.sh
      - ./postgis-schema.sql:/docker-entrypoint-initdb.d/z-postgis-schema.sql

  elasticsearch:
    image: elastic
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  app-data:
  db-data:
  es-data:
