version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: pombola
    depends_on:
      - db
    volumes:
      - app-data:/app-data
      - .:/app
    environment:
      - DATABASE_URL=postgresql://pombola:pombola@db/pombola
      - DATADIR=/app-data
      - DJANGO_DEBUG=TRUE
    ports:
      - "8000:8000"
      - "8001:8000"
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=pombola
      - POSTGRES_PASSWORD=pombola
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  app-data:
  db-data:
